var targets = {
	firstNames: [
		'Gavin',
		'Zoe',
		'Shakespeare\'',
		'Franklin',
		'"Pooky"',
		'Eberhard',
		'Hanako',
		'Justin',
		'Bubbles',
		'Tyler "Whitey"',
		'Stephen',
		'Doug',
		'Will',
		'Marigold ',
		'Captain Murphy',
		'"Shutterbug"',
		'Brendt',
		'"Birdman"',
		'Fredrick',
		'Bucky',
		'JD',
		'Ariel',
		'Snidely',
		'Herb',
		'Charlie',
		'Encyclopedic',
		'John',
		'Stu',
		'Hong',
		'"Nobi"',
		'Terri',
		'Charles',
		'Jess',
		'Igor',
		'Melvin',
		'Count',
		'Bob',
		'Aglaya',
		'Sven',
		'Igor',
		'Georgette',
		'Katharine',
		'Tobias',
		'Ursula',
		'"Goose"',
		'Vlad',
		'Igor',
		'Horatio',
		'Samantha',
		'Lars',
		'Oog',
		'Shane "Big Livin\'"',
		'Tina',
		'Bradley',
		'Toby',
		'Malcom',
		'"Munchie"',
		'Tall Tale',
		'Tight-Lips',
		'Kifkaf',
		'John "Pepperface"',
		'Aisly',
		'Journeyman',
		'DJ Kwin10',
		'Matt',
		'Hobart G.',
		'Shaniqua',
		'Leah',
		'Mekka',
		'Bailey',
		'"Choppy"',
		'Anisul',
		'Robbie',
		'Reggie',
		'Ken',
		'Brian',
		'"Dumbass"',
		'Mikhail',
		'Flynn ',
		'Puff',
		'The Amazing Tetrazini',
		'"Laser Lass"',
		'Templeton',
		'Filly',
		'"Dude"',
		'Nick',
		'"Shrew Master"',
		'Courtney',
		'Roel',
		'Champ',
		'Scout',
		'"G.O.D."',
		'"Boy"',
		'Pinky',
		'Glug',
		'Maurice',
		'John Walker Keg',
		'Nraeneton',
		'William',
		'Dwight',
		'Jackson',
		'Rafulio',
		'Pamela',
		'Nanny',
		'Sudeep',
		'Hiro',
		' FMNH PR2081',
		'Mary',
		'"Dr." Erin',
		'Tank',
		'Julian',
		'Rachel',
		'Marco',
		'Tom B.',
		'Sheila',
		'Trajan',
		'Gat',
		'Krystah',
		'Kiko',
		'Drachus',
		'Art "Argentina"',
		'Roo',
		'Kent ',
		'Faye',
		'Amanda',
		'Bob',
		'Fritz',
		'Frankincense',
		'Bryan',
		'Michael',
		'Soeum',
		'Anya',
		'"Seven Fingers"',
		'Jorgen',
		'Smitty',
		'Sir Abernathy',
		'John',
		'Mr.',
		'Rob "McGomer"',
		'Simon',
		'Pico',
		'Laura "Zippy"',
		'Anna',
		'Bollie',
		'"Long John"',
		'Chuyen',
		'Ashley',
		'Dee',
		'Hiro',
		'Professor',
		'Freddie',
		'Tekada Segal',
		'Junior',
		'Absalom',
		'John "Scruffy"',
		'Francis',
		'Carrot Top',
		'Annie',
		'Bob',
		'Katie (Kat)',
		'Eugene',
		'Matthew',
		'Beetlemike',
		'"Old" Bill',
		'Tina',
		'Mary Ann',
		'"Helical"',
		'"Big Mike"',
		'"Big Chicken"',
		'Karen',
		'Mae',
		'Stephen',
		'Stella',
		'Sharona',
		'Suzie "Ophelia"',
		'The Professor',
		'Katie',
		'Billy "Squirts"',
		'Hailey',
		'Kevin',
		'Lil\' Sebastian',
		'Carlos',
		'Michael',
		'"Prophet" Pat',
		'Logorg',
		'Roddy',
		'Robin',
		'Joe',
		'Harry',
		'Douglas',
		'Malcolm',
		'Fifth',
		'Brian',
		'"Banana Hands"',
		'Lilly',
		'Mari-beth',
		'Jackson H.l',
		'Pendleton',
		'Jessa',
		'Pindergast',
		'Don',
		'Quin',
		'Matt "Coffee and Pie"',
		'Crufty ',
		'Palimpset',
		'Gilbert',
		'Seymour',
		'Cornelius "C.J."',
		'Astro',
		'"Jay the Red Raven"',
		'Dick',
		'Neil',
		'Jason ',
		'Fisher',
		'Max',
		'Porta',
		'"Pogo"',
		'"Grizzly"',
		'Alex "Atom Smasher"',
		'Oliver',
		'Sean',
		'Stephan',
		'Joe',
		'Leslie',
		'Leah',
		'Lucille',
		'Chunk',
		'Ralphado',
		'Will',
		'Leora',
		'Jace',
		'"Insane" Nathan',
		'James',
		'Calvin',
		'Jeremiah',
		'"pikey"',
		'Grant',
		'Periwinkle "The Swami"',
		'Gareth',
		'"Pork Chop"',
		'Marcus',
		'Joe',
		'Betty B.',
		'Donar',
		'"Glowing" Filipp',
		'Lars "The Littlest Viking"',
		'Brandon',
		'Linda',
		'The Duke',
		'Mike',
		'Oliver',
		'Tony',
		'Paul',
		'Apothos',
		'Father',
		'Chartreuse',
		'Seamus',
		'"Swanky"',
		'Royce',
		'Perry',
		'Zellex',
		'Glasses',
		'Seamus',
		'Beefus',
		'Morgan',
		'Dr. Chizmbop',
		'Chao',
		'Joseph',
		'Aron',
		'Gui Bu',
		'Maureen',
		'Glenn',
		'"No Teeth"',
		'Dr.',
		'Haku',
		'George',
		'Shuichi',
		'Hiro',
		'Dr. Marcus',
		'"Mangy"',
		'Gertrude',
		'Melissa',
		'Palmela Handerson',
		'April',
		'Josephine',
		'Mme. Rue',
		'Poindexter',
		'Craig',
		'Peppermint',
		'Geraldine',
		'Foxy',
		'Nobi-Wan',
		'Beatrice',
		'Frank "the Seagull"',
		'Fenton',
		'Hopper',
		'Edward',
		'Geoffrey',
		'Phil',
		'Fabian',
		'Melanie',
		'Melorna',
		'Jack',
		'Carlos',
		'Kittens',
		'Ladyfingers',
		'Stefan',
		'Lando',
		'Bindi',
		'Badger "Badger Badger Badger"',
		'Julia',
		'Caite',
		'Jeff ',
		'Gillen',
		'Kimberlie',
		'Duff',
		'Reginald',
		'Lord Jinty',
		'Finton',
		'"Parrots"',
		'"Slapnuts"',
		'"Twitch"',
		'Aidan',
		'Stickyfingers',
		'Kristoff',
		'"Maniac"',
		'Helen',
		'"Scruffy"',
		'Slink',
		'Armand',
		'Katharine "Kitty"',
		'Dave',
		'Clowny',
		'Chip',
		'Boxxy',
		'"Fat Dave"',
		'Beefy Chuck',
		'Mindy',
		'Billy "Long Legs"',
		'Flora',
		'Big',
		'Barry',
		'Henriki',
		'"Potatohead"',
		'"Montana"',
		'Mary',
		'Christopher',
		'Walter',
		'Earl "The Planet"',
		'Sasha',
		'Elise',
		'Tony',
		'Stanford',
		'Sam',
		'Daniel "The"',
		'Old Man',
		'Tai\'shar',
		'Otto',
		'"Maneater"',
		'"Two Legs"',
		'Willie',
		'James "Jimbo"',
		'Daedalus',
		'Sui Ling',
		'"Bunny"',
		'Geddy',
		'Brandy',
		'Carmen',
		'Kirkland',
		'Helen',
		'Patty "Sweetie"',
		'Terry',
		'Kurt J.',
		'Mrs Muller',
		'"Strobe Light"',
		'"Joey 10-Pins"',
		'Bill',
		'Suzanne',
		'"Captain" Raleigh',
		'Jack-Lorraine',
		'Richard',
		'Arthur',
		'Mr.',
		'Stupid ',
		'Laura',
		'Bengt',
		'Jerome',
		'Jonny "Dangerous"',
		'Andy',
		'Dominic',
		'Ginger',
		'Isaiah',
		'John',
		'Kara',
		'Rosa',
		'Vanessa "Candy"',
		'Animal',
		'Larry',
		'Eric',
		'Tim',
		'Miss',
		'Monty',
		'Romain',
		'Ilaaldo',
		'Thomas',
		'Carlos',
		'Locke',
		'Sean',
		'Craig',
		'Philadelphia',
		'Francis',
		'Mingma',
		'Al',
		'Sven',
		'Andrew',
		'Scott',
		'Jessica',
		'Ivana',
		'Bob',
		'"Buggles"',
		'Cornelius',
		'Clerk',
		'Harry',
		'Jacob',
		'Al',
		'Jack West',
		'Chef',
		'Juan',
		'"l33t"',
		'Cadence',
		'Consuelo',
		'"Big Bad"',
		'"Dead Joe"',
		'"Hobo Joe"',
		'"Karate"',
		'Art',
		'Frank',
		'Trina',
		'Joel',
		'"Stump Juming"',
		'Jimbob',
		'Jeff',
		'Cameron',
		'Jarl',
		'Jolina',
		'Dresden',
		'"Yemen"',
		'Haywood',
		'Igor',
		'Iliana',
		'"Ismurg"',
		'David',
		'Duncan',
		'Romall',
		'Kilroy "2.0"',
		'Mike',
		'Mike ',
		'Jason Telfer',
		'Rhonda',
		'Dianne',
		'Doctor',
		'Chris "Lightning"',
		'Eliza',
		'Holly',
		'Suzi ',
		'Hank',
		'H. H.',
		'Sherlock',
		'Raoul',
		'Claire',
		'Shane',
		'"Beady"',
		'Henry',
		'Slim',
		'Garth',
		'Mitchell',
		'"Hawk Eye"',
		'Morgan',
		'Ande',
		'Star',
		'Dan',
		'Ralph',
		'Felix',
		'Frank',
		'Bobby "Hambone"',
		'Unami',
		'"Smooth Stills"',
		'Gregor',
		'Hans',
		'Melissa',
		'Mme Zabet',
		'Thom',
		'Alexander',
		'"Big Ben Grim"',
		'Dr. Zachary',
		'Harry',
		'Matthew "Wolf"',
		'Dick',
		'Gary',
		'Kelsey',
		'Peter ',
		'Penny',
		'"Nads"',
		'Belle',
		'Meddy',
		'Sammy',
		'Randy',
		'Danzig',
		'Red',
		'Edmund',
		'Robert',
		'Laura ',
		'LaGriffen "Wavelength"',
		'Ernie',
		'Charles "Shaggy"',
		'"Monster"',
		'Gil',
		'Josue',
		'Philip',
		'Gordon',
		'Herb Fritter',
		'Lemuel',
		'Frank "The Bull"',
		'Wilmot',
		'"Snowy"',
		'Herman',
		'Duchey',
		'Hans',
		'Ricky ',
		'Edgar W.',
		'Wilson',
		'Jacques',
		'Gunther',
		'Doug',
		'John',
		'Samuel',
		'Jeoph',
		'Paul',
		'Salvador',
		'Tracey',
		'Granny',
		'Greg',
		'Al "The Greek"',
		'Cecelia',
		'Juan "El Vasco"',
		'Mansuela',
		'Lone ',
		'"Black Widow"',
		'"Evil"',
		'Jameson',
		'Jairdan',
		'Stan',
		'Micheal',
		'Sgt. Ricky',
		'Jack',
		'Whacha',
		'Andy',
		'Gabriel',
		'Ben',
		'Dick',
		'Moeseph',
		'Xavier',
		'Sue',
		'Dmitri',
		'"Big Sal"',
		'Hello',
		'Jane',
		'John',
		'The',
		'Dallas',
		'Jon',
		'Dolores',
		'Mabel',
		'Anna ',
		'Harvey',
		'Tanas',
		'"Loose Lips"',
		'Arthur',
		'Josefa',
		'Emilio',
		'Johnny K.',
		'Silvia',
		'Zynovij "Sin"',
		'King Bob',
		'Jeff',
		'Hermien',
		'Tokyo',
		'"Grimby"',
		'Frasdeed',
		'Luke',
		'Stormageddon',
		'Wellie',
		'Ricky',
		'Drew',
		'Turtle',
		'Erika',
		'Mavid',
		'Shemp',
		'Drizzt',
		'Lancelot',
		'Donovan',
		'James',
		'Mira',
		'Cherith',
		'Ken',
		'J.L. "The Superior Athlete"',
		'Marge',
		'Martin',
		'Richard',
		'Elvia',
		'Carla',
		'Landy',
		'Cornelius',
		'Ballup',
		'Nicolaus ',
		'Sheldon',
		'Weston',
		'Frye',
		'John',
		'Anna',
		'Amy',
		'Alice',
		'Brian',
		'Otis',
		'Santa',
		'Greg',
		'Isaac',
		'"Super-Guy"',
		'Justin',
		'Joanna',
		'Roland',
		'Angela',
		'Moe',
		'Buddy',
		'Not Dave',
		'Pavel',
		'Johnathon',
		'Danny',
		'Waffles',
		'Elise',
		'Jo',
		'Ignacio "Nacho"',
		'"Big Daddy"',
		'Madden',
		'Julie',
		'Wynam',
		'Frances',
		'Robin',
		'Jack',
		'Ghost',
		'Gob',
		'William',
		'Bubs',
		'Radigan',
		'Katarina',
		'Lars ',
		'"Doc" Emmet',
		'Bootsy Bootsy',
		'Dallas',
		'Keegan',
		'Havel',
		'Billy "No Chew"',
		'Antonio "Tony"',
		'"Bramble"',
		'Brick',
		'John',
		'Squirro',
		'Answer',
		'Plus',
		'Tony',
		'Roberto',
		'Father',
		'"Bouncing" Bob',
		'Susie',
		'Josefina',
		'Blank',
		'"Letal" Laiana',
		'Judith',
		'Lana',
		'Tyrone',
		'"Coleman"',
		'Chastity',
		'Tinker',
		'Fanny',
		'Dannerby',
		'Sam',
		'P.J.',
		'Claudia',
		'Papa',
		'Romeo',
		'Becky',
		'"Life Sentence"',
		'Sally',
		'Martin',
		'Hubert',
		'Montgomery',
		'Quentin',
		'Ichi',
		'Jam ',
		'Frodo',
		'Salman "Fish"',
		'Carlos',
		'Ray',
		'Evelyn',
		'"Pot Pie"',
		'Miki',
		'Oksana "The Ocelot"',
		'"Kipper"',
		'Alex',
		'Andy "Analy"',
		'Mash',
		'Lady Elaine',
		'Bobo',
		'"That Guy"',
		'Peter',
		'Lukian',
		'Skar',
		'Tyrone',
		'Rodney',
		'Roxie Summers',
		'Julian',
		'Evian',
		'Tom',
		'Antonio',
		'Jalyss',
		'Bryce',
		'Fidel',
		'Masal',
		'Cheryl',
		'Victoria',
		'Alysha',
		'Emily',
		'Steve',
		'Liam Cunningham',
		'Lars',
		'Carter',
		'Slartibartfast',
		'Winifred',
		'Sylvia',
		'Fuzzy Wuzzy',
		'Caleb',
		'Mina Bobina',
		'#21847',
		'Katie',
		'" Claude: The Hobo King"',
		'Vega'
	],
	lastNames: [
		'Zutenberg',
		'Zevon',
		'Zedders',
		'Youngteeth',
		'Yamada',
		'Xavier',
		'X',
		'Wu',
		'Wong',
		'Wittinger',
		'Windsor',
		'Williguppy',
		'Williams Jr',
		'Williams',
		'Williams',
		'Wilkins',
		'Wienersmith',
		'Wickersham',
		'Whitebone',
		'Whitebirch',
		'Whiplash',
		'Wes',
		'Wells',
		'Weaver',
		'Watson',
		'Wart',
		'Wang',
		'Wan',
		'Waite',
		'Von Straussenhoopen',
		'Von Ribbentrop',
		'Von Kruptenhausen',
		'Von Krampftovin',
		'Von Hackathorn',
		'Volksteinmann',
		'Volkov',
		'Vlishtavlavenhoven',
		'Vlaslavovich',
		'Vermillion',
		'Venture',
		'Venture',
		'Vanelli',
		'Vanderbilt',
		'Van Gogh',
		'Van Der Hooven',
		'Unger',
		'Underscore',
		'Ulrich',
		'Ugh-Ugh the 4th',
		'Ubermensch',
		'"Two Legs',
		'Tutty',
		'Turner',
		'Turnbull',
		'Tudge',
		'Truman',
		'Tribbiani',
		'Tipperary',
		'Tidy',
		'Thyme',
		'Thyme',
		'Thorton',
		'Thompson',
		'Thistlewhite',
		'Thistlebottom',
		'The Voice',
		'the Turret Mecha',
		'the Third',
		'The Swordslinger',
		'the Scot',
		'the Robot',
		'The Pope',
		'the panda',
		'The Numbers Guy',
		'The Nerd',
		'the Manly',
		'The Malignant',
		'The Magic Dragon',
		'The Living Enigma',
		'the lady of lasers!',
		'The Hireable',
		'the Hero',
		'The Gunner',
		'The Gamer',
		'the Fourth',
		'The Filmmaker',
		'The Dutchman',
		'the Dog',
		'The Dog',
		'The Dev',
		'the daddy\'s girl',
		'The Clown',
		'the cavewoman',
		'the Carrier',
		'The baby Taliban',
		'The All-Seeing',
		'Thacker',
		'Terwilliger',
		'Terwilliger',
		'Tallsuit',
		'Szwartz',
		'Swordsmith',
		'Suresh',
		'Superfly',
		'Sue',
		'Sue',
		'Suasar',
		'Strichnine',
		'Strabble',
		'Stork',
		'Stone',
		'Stone',
		'Stewart',
		'Stewart',
		'Stevens',
		'Stevens',
		'Stephenson',
		'Stepenstone',
		'Steinberg',
		'Staun',
		'Standitt',
		'Stamidge',
		'Springs',
		'Spriggs',
		'Spitzensparkz',
		'Spicyface',
		'South',
		'Soup',
		'Sok',
		'Snedden',
		'Smythe',
		'Smorgasbord',
		'Smittson',
		'Smith-Smythe',
		'Smith',
		'Smith',
		'Smith',
		'Smith',
		'Smalls',
		'Sloan',
		'Skott',
		'Skinner',
		'Sivver',
		'Sim',
		'Silverspoon',
		'Siesst',
		'Shujitsu',
		'Sheldon Cooper',
		'Shackleford-Williams',
		'Sensei',
		'Senior',
		'Scruggs',
		'Scrufferson',
		'Scottkeye',
		'Scott Thompson',
		'Schwarz',
		'Schrunkle',
		'Schrodinger',
		'Schlumpter',
		'Schad',
		'Sausagemeister',
		'Saunders',
		'Sassin',
		'Sassafras',
		'Saratoga',
		'Saparelli',
		'Santiago',
		'SanFransisco',
		'Sandusky',
		'Sanders',
		'Sampson',
		'Sales',
		'Safron',
		'S.',
		'Ruoto',
		'Rundle',
		'Rumble',
		'Rudd',
		'Roxbury',
		'Romero',
		'Romeister',
		'Roivas',
		'Rodriguez',
		'Roddington',
		'Robinson',
		'Riley',
		'Righned',
		'Rhyne',
		'Reynolds',
		'Rendition',
		'Redbeard',
		'Reckin\'',
		'Rawlins',
		'Ravensly',
		'Ranmiller, Ph.D',
		'Raines',
		'Rae',
		'Radcliffe',
		'Quixarte',
		'Quinnlan',
		'Quinn',
		'Quacksalver',
		'Pylon',
		'Putzinger',
		'Putz',
		'Purkiss',
		'Pup',
		'Pulloutski',
		'Puller',
		'Pseudonym',
		'Probable',
		'Price',
		'Power',
		'Potty',
		'Portia',
		'Porkens',
		'Polyakov',
		'Poliver',
		'Pogson',
		'Plant',
		'Pizza',
		'Pitt',
		'Pippos',
		'Pinkerton',
		'Pilgrim',
		'Phillips',
		'Pewtersmith',
		'Perell',
		'Penny',
		'Penguin',
		'Pendergast',
		'Pena',
		'Peacekeeper',
		'Paul O\'Donohue',
		'Patterson',
		'Patel',
		'Parkes',
		'Pallini',
		'Page',
		'Packer',
		'Oop',
		'Oodle',
		'Olev',
		'Olafsen',
		'Oglethorpe',
		'Ogle',
		'Of Edinburgh',
		'Ockertz',
		'Ocean',
		'Oblivious',
		'O\'Toole',
		'O\'siris',
		'O\'Shannon',
		'O\'Plenty',
		'O\'Neill',
		'O\'hara',
		'O\'Doyle',
		'O\'Dontal',
		'O\'Connel',
		'O\'Brien',
		'O\'Brian',
		'O\'Brady',
		'Nuzzo',
		'Not the Abacus',
		'Normandy',
		'Nistal',
		'Nimzowitsch',
		'Ngyen',
		'Newton',
		'Nerdlinger',
		'Nelson',
		'Nasty',
		'Namatata',
		'Naked',
		'Nakano',
		'Nagima',
		'Muttisberger',
		'Mutt',
		'Mullberry',
		'Muffet',
		'Ms. Handy',
		'Moseby',
		'Moriarty',
		'Morgana',
		'Morgan',
		'Moreland',
		'Moon-Rictor',
		'Monroe',
		'Monoxide',
		'Miyakusa',
		'Minxington',
		'Milosauski ',
		'Miller',
		'Miller',
		'Miles',
		'Miksyezpitlick',
		'Mias',
		'Mewell',
		'Metz',
		'Merriweather',
		'Meov',
		'Mendecino',
		'McTavish',
		'McSchoolbus',
		'McMullan',
		'McMillan',
		'McMahon',
		'McLlyllyqgk',
		'McLemons',
		'McKittenplan',
		'McKenzie ',
		'McKelvie',
		'McGuire',
		'McGruff',
		'McGrandypants',
		'McGinty III',
		'McGill',
		'McGherkin',
		'McGee',
		'McGee',
		'McGee',
		'McGee',
		'McGann',
		'McDonald',
		'McDonald',
		'McDermont',
		'McDerm',
		'McCoy',
		'McCoy',
		'McCown',
		'McClownface',
		'McCallahan',
		'McBride',
		'McAwning',
		'Maynard',
		'Maynard',
		'Mayers',
		'Maxwell',
		'Matt',
		'Matherson',
		'Matalamaki',
		'Masterton',
		'Masterson',
		'Mary',
		'Martin',
		'Marks III',
		'Markowski',
		'Mark',
		'Marchant',
		'Marascino',
		'Mantleford',
		'ManorSkeleton',
		'Mann',
		'Mann',
		'Mandarb',
		'Man',
		'Malone, PhD',
		'Malone',
		'Makeit',
		'Makaronas',
		'Maizeman',
		'Mai',
		'MacLeod',
		'MacLeod',
		'MacIntosh',
		'MacGuffin',
		'MacDoogle',
		'Macdonald',
		'MacDangledornery',
		'MacAllister',
		'Mac',
		'Lynley',
		'Luther',
		'Lunetta',
		'Luckless',
		'Luckless',
		'Lu Sol',
		'Lorraine-Jack',
		'Long',
		'Loman',
		'Little',
		'Lisa',
		'Linkletter',
		'Lima',
		'Liao',
		'Li',
		'Leonard',
		'Lemercier',
		'Lee',
		'Lee',
		'Lee',
		'Lee',
		'Lee',
		'Lee',
		'Lecter',
		'Leatherface',
		'Leath',
		'Leane',
		'Leading',
		'Leader',
		'Le Tuss',
		'Lawrence',
		'Latzel',
		'Lastname',
		'Lamora',
		'Lambert',
		'Lage',
		'Lac',
		'La Rouge',
		'Kukuli Sherpa',
		'Koholic',
		'Knutsen',
		'Klynsmith',
		'Kimber',
		'Kilroy',
		'Killieu',
		'Kelso',
		'Kelly',
		'Karstens',
		'Kant',
		'K.K. Patterson',
		'Justice',
		'Just Al',
		'Junior',
		'Julie',
		'Juanberg',
		'Jones',
		'Jones',
		'Jones',
		'Jon',
		'Johnson',
		'Johnson',
		'Johnson',
		'Johnson',
		'Johnson',
		'Johnson',
		'Joelle',
		'Jimmy',
		'Jimbobski',
		'Jeffries',
		'Jay',
		'Jarlsson',
		'Japes',
		'Jameson',
		'James',
		'Jablomie',
		'Ivanovich',
		'Ivanov',
		'Isaac von Murg III',
		'Iklam',
		'Idaho',
		'Hyperion',
		'Hutchins',
		'Hunt',
		'Huns- Tinks',
		'Hubert Telfer',
		'Hubert',
		'Hoskings',
		'Horrible',
		'Hopkins',
		'Hopkins',
		'Hooray!',
		'Homewreker',
		'Homebrew',
		'Holmes',
		'Holmes',
		'Hoffary',
		'Hodges',
		'Herberts',
		'Henry',
		'Hendricks',
		'Henderson',
		'Heaver',
		'Heath',
		'Hawkins',
		'Hawkins',
		'Hassle',
		'Hasowitz',
		'Harmon',
		'Hapshatz',
		'Happer',
		'Hangnail',
		'Hammerelli',
		'Hakama',
		'Gunther Rawlings',
		'Gumtree',
		'Gruuber',
		'Grundwald',
		'Groznaya',
		'Groodbort',
		'Grimlock',
		'Grey',
		'Grey',
		'Greenback',
		'Green',
		'Grayson',
		'Gray',
		'Grammer',
		'Gozinya',
		'Gower',
		'Gorgonzola',
		'Goose',
		'Gone',
		'Goldheart',
		'Goldberg',
		'Gibraltar',
		'Ghost',
		'Gertrude',
		'Geroge',
		'George',
		'Geoffries',
		'Gasterson',
		'Gaskin',
		'Garageman',
		'Gamesh',
		'Gagnonian',
		'Fry',
		'Froman',
		'Fritz',
		'Frilby',
		'Fredrickson',
		'Frederickson',
		'Freddy',
		'Frankzapper',
		'Francois',
		'Forecastle',
		'Flintoff',
		'Flintlock',
		'Flimpkin',
		'Flambeaux',
		'Five-Aces',
		'Fitzgerald',
		'Finnemore',
		'Figgens',
		'Fifferson',
		'Ferris',
		'Faust',
		'Fantastic',
		'Fandango',
		'Fallspeth',
		'Falafel',
		'Fairmaiden',
		'Etchegoyen',
		'Estrada',
		'Endling',
		'Egan',
		'Edison',
		'Earlwick',
		'Dusaquin III',
		'Dupp',
		'Dunwitch',
		'Dunkel',
		'Dunger',
		'Duin',
		'Dudley',
		'Dubois',
		'Dover',
		'Dorkly',
		'Dope',
		'Donovan',
		'Donnim',
		'Domovoi',
		'Domingo',
		'Dolly',
		'Doe',
		'Doe',
		'Doctor',
		'Dixon',
		'Ditty',
		'DiNapoli',
		'Dilly',
		'Diggs Well',
		'Diana',
		'DeVille',
		'Desai',
		'Dent',
		'Delgadillo',
		'Dedwuman',
		'DeCastillac',
		'Deatherage',
		'De Mortale',
		'de Bob',
		'Davis',
		'Davies',
		'Davies',
		'Dauncey',
		'Dasknowmann',
		'Dasame',
		'Dark Lord of All',
		'Danger',
		'Dang',
		'Dandruff',
		'Dan',
		'Dalton',
		'Dalki ?',
		'Da Stooge',
		'D\'ourden',
		'D\'Chomp',
		'D. Donovan',
		'Cutter',
		'Cutter',
		'Cutestory',
		'Custo',
		'Cugno',
		'Crocker',
		'Crieff',
		'Cranium',
		'Cox',
		'Corrin',
		'Corrigan',
		'Corpenicus',
		'Cornocallskeek',
		'Copernicus',
		'Coper',
		'Cooper',
		'Cooke',
		'Cooke',
		'Condor',
		'Coldwell',
		'Coldwater',
		'Clinkingbeard',
		'Cleetusbury',
		'Claus',
		'Clarkke',
		'Clarke',
		'Clark',
		'Ciderview',
		'Chutneigh',
		'Chorale',
		'Cho',
		'Cheezmo',
		'Charles',
		'Chappelle, seriously',
		'Chang',
		'Celestia',
		'Catt',
		'Cat',
		'Carruthers',
		'Candy',
		'Calderon',
		'Caine',
		'Cain',
		'Cabrera',
		'Bynam',
		'Butterface',
		'Buttcuddle',
		'Butt',
		'Buster',
		'Buster',
		'Burnside',
		'Bunny',
		'Bumple',
		'Buckworth',
		'Brudel',
		'Brown',
		'Brown',
		'Brown',
		'Brown',
		'Broddenbury',
		'Brochu',
		'Bright',
		'Boswell',
		'Boss',
		'Boru',
		'Bordiardo',
		'Booth',
		'Book',
		'Bonitichi',
		'Bond',
		'Bob',
		'Blitzkrieg',
		'Blincken',
		'Blankenship',
		'Blanche',
		'Blanca',
		'Birch',
		'Bingle',
		'Biggums',
		'Benny',
		'Bellefleur',
		'Bell',
		'Beeflift',
		'Beckon',
		'Becket',
		'Bearington',
		'Bear',
		'Bear',
		'Bautista',
		'Basil',
		'Bartwoski',
		'Bartlet',
		'Bartholemew',
		'Barnstorm III',
		'Barnes',
		'Barnes',
		'Banoir',
		'Bamfery',
		'Baggins',
		'Babu',
		'Arrizaga',
		'Archer',
		'Appleheart',
		'Appleby',
		'Aoba',
		'Antonov',
		'Aloysius',
		'Alien',
		'Ali',
		'a\'Dar',
		'(security clearance needed)',
		'(No Last Name)',
		'"You know, Him"',
		'"V"',
		'"The Unknown"',
		'"The Unblemished"',
		'"The Tyrone"',
		'"The Rod"',
		'"The Red Viper"',
		'"the nut"',
		'"the Naive"',
		'"the Monster"',
		'"The Machine" Alfonso',
		'"The JJJJ"',
		'"The Ginger"',
		'"The Fiddle"',
		'"The Efficient"',
		'"The Dandruff"',
		'"The Constitution" Jones',
		'"The buzzkill"',
		'"The Bossman"',
		'"Snake-Eyes"',
		'"Sly Bacon"',
		'"Mongo" Monkeyteeth',
		'"Lucky Boy"',
		'"It\'s not important."',
		'"Four-Eyes"',
		'"Diamond" Platherson',
		'"Cuddly Wuddly"',
		'"Cookie"',
		'"Beena"',
		'"Alexander"',
		' McShinty',
		'"The Dog"'
	],
	excitedBy: [
		'Granny Crafts',
		'Chinese Food',
		'Nachos',
		'spicy things',
		'Food',
		'Games',
		'particle physics',
		'Tight clothing',
		'Research',
		'Hockey',
		'Girls',
		'Hobby: an artform or craft',
		'Soda',
		'Female movie stars',
		'Public expressions of emotion',
		'Apple computers',
		'Family Events',
		'musical instruments beginning with the letter b',
		'genetic anamolies',
		'Photography',
		'Transportation',
		'Graveyards',
		'Things that are sweet',
		'Hobby involving animals',
		'Danger',
		'Household Impliments',
		'Equations',
		'"Explosion noise, Sci-Fi sound effects, Guns & Kittens"',
		'movie marathons',
		'Colors',
		'Something found in an office',
		'Loud voices',
		'Paperwork',
		'Pointy Things',
		'Something Loud',
		'Day dreams',
		'Food',
		'Opera',
		'Addiction: something generally non-addictive',
		'Discounts',
		'Detective/Lawyer crossovers',
		'Clothes',
		'Hobby : watching a sport',
		'Household Decor',
		'Outer Space',
		'Animals',
		'Dirty movies',
		'himself',
		'Inventions',
		'Petty Crimes',
		'Things that clean other things',
		'Toys',
		'Women',
		'Retirement',
		'Food',
		'Well-known locations of historical significance',
		'Italian food',
		'Strange collection',
		'Religion',
		'Beverage creation',
		'Things named after mythical animals',
		'Striped Clothing',
		'Muscle cars',
		'neatness',
		'Minutiae',
		'Shopping',
		'Internet Memes',
		'Unnatural Foods',
		'Weapons',
		'Types of weather',
		'Collecting Useless Items',
		'Plungers',
		'plants',
		'Bar Hopping',
		'Food',
		'Common social interactions',
		'Cute and Fluffy things',
		'Nature',
		'Pyrotechnics',
		'Pump lasers',
		'Task that is generally considered tedious',
		'iPods',
		'Geeky Stuff',
		'Imitations',
		'The Machine of Death',
		'Food',
		'Small woodland creatures',
		'chewing things',
		'video games',
		'Food',
		'things found in the back of a closet',
		'Colors',
		'Animal skins',
		'Heightened physiological ability',
		'music',
		'Pranks',
		'Orange Juice',
		'Beverages',
		'Bells of all shapes and sizes',
		'Gambling',
		'The Sahara desert',
		'Objects d\'art',
		'Cricket',
		'A group of people',
		'Hunting',
		'Attention',
		'pseudoscience',
		'Chemicals',
		'Things which are green',
		'Dancing',
		'Wrestling',
		'Things that are symmetrical',
		'avant garde art',
		'Alchol',
		'Firearms',
		'Fall Rush',
		'Fanfiction',
		'Alcoholic Beverages',
		'Pottery',
		'sports',
		'Video Games',
		'The Rapture',
		'Fudge',
		'Golf',
		'Bright lights',
		'Exotics',
		'Pals!',
		'A foodstuff',
		'Anime',
		'Renovating houses',
		'New Medical Procedures',
		'Having fun with friends',
		'Throwing things',
		'Architecture',
		'Watching paint dry',
		'Apparel',
		'The Color Purple',
		'Role playing',
		'Animals',
		'hanging out with friends',
		'Big rocks',
		'Trash novels',
		'Boxes',
		'Uncovering secrets',
		'Doing Her Job',
		'addiction',
		'Cartoons',
		'Comic Books',
		'Nostalgia for something that no longer exists',
		'fashion accessories',
		'Ants',
		'Technology',
		'mundane jobs',
		'Large group of likeminded people',
		'Props',
		'Mideval Power Struggles',
		'Monkeys',
		'Science',
		'minimum wage employees',
		'Video Games',
		'Obscure Bands',
		'Explosions',
		'Musicians',
		'violence',
		'Running',
		'Hobby: a sport',
		'Days off work',
		'Games of Strategy and Stealth',
		'sweets',
		'Car racing',
		'Animals',
		'Money',
		'Communications',
		'Furry cute animals',
		'Little victories',
		'A certain sound',
		'Foreign languages',
		'The media',
		'Food',
		'Voyeurism',
		'Scientific breakthroughs',
		'Purple things',
		'Squashes',
		'Loud Noise',
		'Birds of all kinds',
		'buttons',
		'Flightless birds',
		'medical equipment',
		'Doing a job',
		'Google',
		'Vitamins',
		'Fighting',
		'tiny cute animals because they are so adorable and you just want to cuddle them and  *SQUEEE*',
		'Architecture',
		'Hobby: something competitive',
		'Alternative music/instruments',
		'A very physical activity',
		'Destruction',
		'Knightly deeds, windmills, giants',
		'Tabletop Games',
		'miniatures',
		'Things you see when stuck in traffic',
		'Everyday events',
		'Obsession: Food, unhealthy',
		'Tests',
		'discounted objects',
		'Pet Treats',
		'"Pranks"',
		'Adventure',
		'art',
		'daydreams',
		'Rainbows',
		'Animals',
		'Politically incorrect collectibles',
		'The internet',
		'Badges',
		'Really tiny cute things',
		'Large Things',
		'Crystals',
		'Literature',
		'Ingredients',
		'Breakfast foods',
		'Marine life',
		'Utility',
		'Promo Cards',
		'Expensive Wheels',
		'Video Games',
		'Art',
		'An instrument',
		'Death',
		'Musical Instruments',
		'Acrobatics',
		'Taking Pictures',
		'bargains',
		'Record Shops',
		'Light',
		'Loud Noises',
		'Rock Music',
		'Mass Media',
		'Packaging materials',
		'Festivals',
		'Danger',
		'The color green',
		'Hobby: Dangerous, but legal, activity',
		'liquids',
		'Woolen Clothing',
		'Shooting',
		'Interesting Hats',
		'Treasure hunting',
		'Performing',
		'Food',
		'Murder',
		'tall people',
		'Large-scale performance pieces',
		'Saturday Morning Cartoons',
		'Paper mache',
		'a breakfast food',
		'Disease',
		'The Past, Your Present',
		'Academia',
		'Secret knowledge and/or knowledge of something secret',
		'Ladies hosiery',
		'Niche documentaries',
		'Engineers',
		'Alcohol',
		'Food',
		'Board games',
		'Fame',
		'Obsession: Smells',
		'Sexual fetish',
		'Soft food',
		'Power',
		'Food',
		'Fabrics',
		'Snacks',
		'Mathematics',
		'The plays of Henrik Ibsen',
		'Capes',
		'Gambling',
		'Delicious food',
		'Fresh Produce',
		'Other people with a particular trait',
		'Things that have gone out of fashion',
		'Alternative medicine',
		'GLAD products',
		'Office supplies',
		'Money',
		'Hobby: Something people train for years to master',
		'Word Games',
		'Sci-Fi sound effects, Explosion Noise & Kittens',
		'Hobby: something most people hate doing',
		'attention',
		'Very small objects',
		'Shiny Objects',
		'Music',
		'Sports',
		'Dead animals',
		'New Game Concepts',
		'Fine dining',
		'Obtaining knowledge',
		'Screechy Noises',
		'Party Snacks',
		'Listening to people talk',
		'An Exquisite Loaf of Pumpernickle',
		'Food',
		'branding',
		'Nostalgia',
		'Podcasts',
		'Vegetables',
		'The weird stuff',
		'Film ',
		'Music',
		'Engineers',
		'Horses',
		'Explosions',
		'Vehicles',
		'Dinosaur Fossils',
		'Cows',
		'An animal with four legs',
		'Conspiracies',
		'Thrill riding',
		'Items of Sentimental Value',
		'travel',
		'Tiny things',
		'Visitors',
		'Odd shaped fruit',
		'Toys',
		'Clean Socks',
		'Imaginary things she thinks are real',
		'weird rock bands',
		'Older women',
		'solving puzzles',
		'Everything',
		'Loud explosions, small cakes',
		'Tools',
		'Clowns',
		'Things That Look Cozy',
		'Art',
		'Playing baseball',
		'Sport most people have never heard of',
		'Organic things',
		'Black and white',
		'poultry',
		'Toenails',
		'Outdoor games',
		'Favorite food',
		'Something in the air',
		'Thailand',
		'Endangered animals',
		'retail chains',
		'Scrapbooks',
		'life',
		'High-tech/science fiction device',
		'Food',
		'Empty Places',
		'Construction Hardware',
		'Pornography',
		'$',
		'Adulthood',
		'TV',
		'Flight',
		'Family',
		'Hobby: Outdated activity',
		'Kitsch',
		'Cooking',
		'Outwitting young children and world travel',
		'a dangerous hobby',
		'Tea',
		'airport restrooms',
		'Playground equipment',
		'Space',
		'Table top games',
		'Killing',
		'Vocabulary',
		'Very little',
		'A lot of things',
		'Things that are stolen',
		'Fire',
		'expensive things',
		'Patio furniture',
		'Things on the ground',
		'leather',
		'Tiny Headwear',
		'flags',
		'Hot things',
		'Cats',
		'Problem solving',
		'Speaker systems',
		'Things that are intangible',
		'A very nerdy pursuit',
		'Sweets',
		'Millions of adoring fans',
		'Precious metals',
		'Kink',
		'Wines',
		'Normal Daily Events',
		'Hot Oil',
		'Explosives',
		'currency',
		'1970s Cop Shows',
		'Pissing',
		'food',
		'roleplaying games',
		'Being Touched',
		'Red heads',
		'Crafts',
		'Electronics',
		'unbrokenness ',
		'Art',
		'celestial observations',
		'Champagne',
		'Exercise',
		'Theology',
		'Efficiency',
		'Summer Olympic Sports',
		'Horses',
		'Stitches',
		'Felines',
		'Fancy Things',
		'Heroine',
		'golf',
		'A particular stature or body type',
		'Incidents and accidents',
		'Stones',
		'Strange foods',
		'Literature',
		'anonymous forums',
		'Steam punk',
		'Something common only in the tropics',
		'Polygons',
		'Nothing',
		'rail lines',
		'A cultural item from the 1980s',
		'Music',
		'Subterranean Features',
		'People with a particular trait',
		'repetitive things',
		'scratching',
		'Collecting Sharp objects',
		'surfing',
		'Food',
		'War',
		'music',
		'Pop Culture references',
		'Film',
		'fresh laundry',
		'Doors',
		'Unpopular Winter Sport',
		'Hobby: Collecting useless stuff',
		'machinery',
		'Exotic features in women',
		'Science Fiction',
		'Conspiricy Theories',
		'Crafts',
		'seafood',
		'Weather',
		'thoughts of romance',
		'Money',
		'Frozen yogurt',
		'Underpracticed party trick',
		'Mixed Martial Arts',
		'Long Bombs',
		'"offensive humor"',
		'Psychedelic Drugs',
		'Opportunity',
		'Mysteries',
		'Quantum jumping',
		'Wildlife',
		'electricity',
		'Rhythm',
		'Going to the zoo',
		'smell of sawdust',
		'Something found in a casino',
		'Trains',
		'Working',
		'Shiney objects',
		'Hiatus',
		'Round Objects',
		'Vodka',
		'Musicals',
		'Astronomy',
		'the chase',
		'Vegetables',
		'Obscure weaponry',
		'small rodents',
		'Extreme Sports',
		'Cavewomen',
		'Round Things',
		'shiny things',
		'Textures',
		'Objects that are smaller than they should be',
		'Catching liars',
		'Chemical reactions',
		'Birds',
		'Weapons',
		'Adventure',
		'Crackers',
		'Being invited to parties',
		'Dancing',
		'Nature',
		'The finer things in life',
		'unknown',
		'Surrealist Artists',
		'Action Stories',
		'Complications',
		'Things we take for granted',
		'Heroes',
		'A heightened physical ability',
		'Technology',
		'hammers',
		'Metal Headwear',
		'Beer',
		'Baked Goods',
		'Conspiracy theories',
		'Fighting',
		'Microorganisms',
		'Video Games',
		'Genetically Engineered Animals',
		'Animals',
		'Obscure research',
		'Cleanliness',
		'Loud noises.',
		'Numismatics',
		'Dairy products',
		'Bad actresses with butterfaces, hair gel and sunscreen',
		'toes',
		'Great Deals',
		'Out-of-the-ordinary transportation',
		'Racing',
		'Old-school flying machines',
		'Video Games',
		'Travelling',
		'Ghost Stories',
		'John Wayne',
		'Order',
		'Hobby: something mechanical',
		'Spirals',
		'Films',
		'Whips & Chains',
		'finding old lead type',
		'Wealth',
		'Pink',
		'Collecting',
		'Promises',
		'Things with feathers',
		'African Animal',
		'Medical Tests',
		'office supplies',
		'Fresh food',
		'drugs',
		'Alien Life',
		'Live animals',
		'Free Trading Cards',
		'people not getting permits for work being done',
		'Motor Sport',
		'Film memorabilia',
		'Sports',
		'menial tasks',
		'Food',
		'Reruns on TV',
		'Wordplay',
		'Doilies',
		'Making money',
		'Parrots',
		'Helping others',
		'Jane Doe',
		'Mystery',
		'Exclusive Clubs',
		'Candy',
		'Cosmic forces',
		'Word, expression, saying, figure of speech, or quote',
		'Nature',
		'Small Things',
		'Gardening Equipment',
		'Obscure Historical Facts',
		'Warm Drinks',
		'Housework',
		'Gathering data',
		'loose women',
		'Technology',
		'Truck-related items',
		'Blood sports',
		'Fancy Suits',
		'Gambling',
		'Nature',
		'Hot drinks',
		'Sightseeing',
		'Ceramics',
		'Mammalian liquid',
		'6" spiked stilettos',
		'Internet Access',
		'Clean Floors, Brooms, Cut Hair',
		'Pizza',
		'collecting',
		'Old things',
		'helping out',
		'His sword',
		'Antiques',
		'Vehicles',
		'Anything sharp',
		'Medival Weapons',
		'Women',
		'Rotating objects',
		'Entertainment: Sci-fi movies',
		'Bulimics',
		'Potatoes',
		'Emergancy tools',
		'top secret projects',
		'books',
		'Traveling',
		'loud noises',
		'Condiments',
		'Stars, Planets',
		'Physics',
		'Artisinal Cheese',
		'Lace',
		'Comics',
		'Adrenalin',
		'Close proximity to people',
		'Foreign affairs',
		'Things that are on fire',
		'Sex toys',
		'Hurting animals',
		'Trading Cards',
		'Human contact',
		'Crime',
		' Women over a certain age',
		'Music',
		'work',
		'Things that make her look good in front of others',
		'womens\' garments',
		'war machines',
		'Automobiles',
		'A Snack Food',
		'Eating Food',
		'Shiny things',
		'Catnip',
		'Messes',
		'Shiny things',
		'Fancy clothing',
		'Smooth music',
		'sentences',
		'Baby\'s clothes',
		'Puzzles and Sci Fi Culture',
		'Nostrils',
		'a socially awkward event',
		'Shiny Things',
		'Night',
		'Illusions',
		'Fortifications',
		'Carrots',
		'Casserole',
		'Coloured Liquids',
		'Accidents',
		'Science',
		'shiny things',
		'Seafood',
		'Danger',
		'Technology',
		'Awards',
		'The Future',
		'Shiney objects',
		'Making beats, animal tattoos, and jewelry',
		'Violence',
		'A Kind of Event',
		'Puzzles',
		'Data',
		'Blood',
		'Steampunk',
		'Hearing the confessions of sinners',
		'Surprises',
		'Clouds',
		'Crafts',
		'Paintbrushes',
		'Pet birds',
		'Gambling',
		'Fame',
		'Warmth',
		'Pointy Things',
		'Wordplay',
		'Men',
		'delicious meat',
		'Playing with Katana',
		'Futuristic Technology',
		'Type of Clothing',
		'numbers',
		'Comic Books, Good Food & getting tattoos. ',
		'Flying Things',
		'Leafy Greens',
		'pimped-out cars',
		'Power',
		'suits',
		'Dangerous Pursuits',
		'Danger',
		'Sports',
		'A hobby',
		'Rebellion',
		'Beer',
		'A sport',
		'Guns and women',
		'Photography',
		'High and Dangerous',
		'Scents',
		'Collecting Weapons',
		'Men in Uniform',
		'Don Knott\'s Films',
		'Farm Animals',
		'porn',
		'Heroic Characters',
		'Experience or indulgence this person will never turn down',
		'Acticities in the Great Outdoors',
		'Stuff',
		'horror',
		'Gems',
		'Clogs',
		'Prophecy',
		'Something spherical',
		'High-Risk Situations',
		'Really good italian food',
		'Small plants',
		'Ancient Books',
		'smells',
		'Extreme Sports',
		'Famous Women',
		'Bad puns',
		'A job well done',
		'Shampoos',
		'Transportation',
		'The misfortune of others',
		'Baby animals',
		'Charged particles',
		'Big Machinery',
		'Post-Its',
		'The reemergence of childhood fears',
		'Dramatic Landscapes',
		'College Subject',
		'Money',
		'Praise',
		'Technology',
		'Recieving credit/gifts for something she did\'nt do',
		'Encyclopedias',
		'Fruit',
		'Politics',
		'Electronics'
	],
	hinderedBy: [
		'Speech Impediments',
		'Actors',
		'a rotator cuff inhury',
		'tiny hands',
		'Medical condition',
		'Fear',
		'feelings of inadequacy',
		'Chronic back pain',
		'Lack of Funding',
		'Fear',
		'Lack of freedom',
		'Phobia of an animal',
		'Insects',
		'Male Movie stars',
		'Obsessive Compulsion',
		'Bananas',
		'Contract',
		'uncommon disease',
		'facial deformity',
		'An obsession with an item',
		'"The Man"',
		'The Faculty',
		'Mental State',
		'A secret addiction',
		'Libido',
		'Severe Phobia',
		'Eyewear',
		'Sugar Cravings & a need to torture miniature dogs.',
		'brushes with the law',
		'Medical Condition',
		'An uncommon animal',
		'Disability',
		'Community Organizations',
		'A fear of hedge trimmers',
		'An Addiction',
		'Alcohol',
		'education',
		'Sylvester Stallone movies',
		'Tragic flaw',
		'Addiction',
		'Lack of knowledge',
		'Wieght',
		'psychological disorder',
		'A paradox',
		'Communications',
		'Foot Problems',
		'Addiction',
		'Megadeth',
		'Social Etiquette',
		'Mistaken Belief',
		'Physical disability',
		'Vegetables',
		'Electricity',
		'Party politics',
		'lack of intelegence',
		'Allergy to a common food',
		'Vision Impairment',
		'Unusual phobia',
		'Religion',
		'Addiction to hard to find substance',
		'Lack of body parts',
		'flying animal',
		'Easily distracted',
		'Anything not parallel or perpendicular to something else',
		'Crippling Fear',
		'Narcissism',
		'Faulty Parts',
		'Obsessive Compulsion',
		'Memory Problems',
		'Unusual Fears',
		'Mental Illness',
		'Papal Bulls',
		'uncommon phobia',
		'Food',
		'Strange Thought Patterns',
		'Obsessive Compulsion',
		'Severe Allergies',
		'A fact of life',
		'Dynamite Difficulties',
		'her secret weakness',
		'His Greatest Weakness',
		'Dust',
		'Language Barriers',
		'Poor eyesight',
		'Knowledge of something nobody should know',
		'Low constitution',
		'Popular Bands',
		'low muscle tone',
		'his parents',
		'Laziness',
		'Problems with being short',
		'Noise',
		'Poor living conditions',
		'Addiction to a hobby',
		'furniture',
		'Omniscience',
		'Short sighted',
		'Physical Appearance',
		'Stickiness',
		'Compulsiveness',
		'Sniffing glue',
		'Pointy Pointy Plants',
		'His wife',
		'Negative character trait',
		'Size',
		'Nothing',
		'logical reasoning',
		'A disability',
		'Height and Depth',
		'Nervousness',
		'Speech impediment',
		'Fear of small, living things',
		'Disorganization',
		'Time',
		'Physical disability',
		'poor complexion',
		'Personality Flaws',
		'An uncontrollable urge',
		'Whiteness',
		'back injury',
		'Household chores',
		'Science',
		'Fear of enclosed spaces',
		'Nervous problem',
		'Canes',
		'Finances',
		'the ability to draw',
		'A missing body part',
		'Corporate ideals',
		'Colleagues',
		'"One Size Fits All" ',
		'Superstition',
		'Open spaces',
		'Social Problems',
		'Crippling boredom',
		'Garbage cans',
		'Always running late',
		'Education',
		'Zookeepers',
		'teachers',
		'Deserts',
		'Eyesight',
		'Red Tape',
		'Feelings of being watched',
		'Other Profession',
		'allergy to something rare, but not rare enough',
		'Floors',
		'People Skills',
		'Phobia of something inescapable',
		'his movie career',
		'Dance Music',
		'Industrial Accident',
		'handicap',
		'A crippling fear of certain objects',
		'Humor',
		'A fondness for cats',
		'Authority',
		'A constant fear',
		'appearance',
		'Bathing',
		'Bright lights',
		'Religious views',
		'Self image',
		'physical disability',
		'Stairs',
		'Allergy to a synthetic substance',
		'Crippling phobia',
		'Her Co-workers',
		'too much work',
		'Injury',
		'Reality',
		'Outdated technology',
		'Creating alarm',
		'Daily life',
		'Furniture,stairs,flat surfaces',
		'Disease',
		'Personal belongings',
		'Redheads',
		'Being dead',
		'Financial problems',
		'Social interaction',
		'Hallucinations',
		'Treestumps',
		'Slippery Tools',
		'Poor conversational skills',
		'lots of buttons',
		'Fear',
		'circadian rhythms',
		'The Government',
		'His lack of computer skills',
		'Cutting Objects',
		'Lawsuits',
		'ADHD because you know sometimes it\'s hard to concentrate on what you are... Oh Sheila just texted me a picture of her puppy! Isn\'t he cute?',
		'Compulsion',
		'Phobia of something invisible',
		'Rediculous prejudice',
		'cognitive memory',
		'A Chronic Condition',
		'Mental state',
		'Sense',
		'An addiction',
		'Good luck',
		'Superfast metabolism',
		'Nemesis: Authority figure',
		'Insurance Companies',
		'a social anxiety',
		'Tiny Insects',
		'Apperance',
		'A pact with a dark force',
		'romance',
		'Averageness',
		'Daddy issues',
		'Halatosis',
		'"Easily distracted"',
		'Books',
		'Oprah',
		'Religion',
		'Phobia',
		'Science',
		'Other people',
		'Bugs',
		'Things younger than her',
		'Love',
		'Tactile',
		'Amount of bathroom use',
		'Genetic illness',
		'Music',
		'Her dreams',
		'An unfortunate supernatural power',
		'Annoyances',
		'Commitment issues',
		'Weight',
		'Refuses to use an important tool',
		'addiction',
		'Irrational fear of mobility devices',
		'Gastric Distress',
		'Vehicle failure requring a mechanic',
		'Body Parts',
		'smells',
		'Crippling fear of the unknown',
		'Voice',
		'Sports Teams',
		'English',
		'Physical trait: Tiny and/or missing feature',
		'an illness',
		'Reality',
		'Verbal Gaffes',
		'Speech Impediment',
		'Character flaw',
		'Mental affliction',
		'Personality',
		'emotion',
		'vow of chastity',
		'Obsessive-compulsive disorder',
		'Thanatophobia (The Fear of Death)',
		'Missing limbs',
		'A learning disability',
		'Phobia of the mouth',
		'Predestination Paradoxes',
		'Neurosis',
		'Something that does not exist',
		'Chemical imbalance',
		'Strangely cute distractions',
		'Needles',
		'A disability',
		'"Poor vision"',
		'Health condition',
		'Sore feet',
		'Bugs',
		'Aversion to a social situation of some kind',
		'Poor Communication Skills',
		'Inattention to Detail',
		'Illness',
		'Roommates',
		'Phobia of loud noises',
		'Communication',
		'a thick Austrian accent',
		'Krypton',
		'Allergies',
		'Fear of sitting down',
		'Upper Body',
		'Secret Obsession: Something that is legal but shouldn\'t be',
		'Eye problems',
		'Bureaucracy',
		'Family members',
		'Fear',
		'her past',
		'An irrational hatred of something most people love',
		'"Psychological Difficulties"',
		'Sugar Cravings & small dogs.',
		'Phobia of something naturally occurring',
		'allergies',
		'Shortcommings',
		'Darkness',
		'Clothing',
		'Nerds',
		'his phobia',
		'Counting',
		'Family',
		'Agoraphobia',
		'His Diet',
		'Home Improvement supplies',
		'Addiction',
		'Science',
		'Physical Impairment',
		'weight',
		'Difficult questions',
		'Ruminants',
		'Stairs',
		'Lawn ornaments',
		'Dislike of people ',
		'Money',
		'Ability to Flirt',
		'Technological Progress',
		'Hooked on a pointless activity',
		'Steep mountain slopes',
		'Creepy bugs',
		'Goats',
		'Food that is orange',
		'Delusions',
		'Trouble with the law',
		'Uncontrollable rage specific to domestic pets',
		'overthinking',
		'Knives',
		'Fashion',
		'Upward mobility',
		'Heat',
		'Not Being Able to Find Women\'s Clothing that Fit',
		'Inappropriate clothing',
		'back problems',
		'Unknown Allergy',
		'portals and giant insects',
		'Trolls',
		'Secret phobia',
		'Vision impairment',
		'Age',
		'Strange Weather',
		'Her Body',
		'things that hang on the wall',
		'Erectile Dysfunction',
		'His long name',
		'A Number',
		'garments',
		'Toenails',
		'Lack of sleep',
		'A secret shame',
		'Physical Impairment',
		'Obesity',
		'Skin problem',
		'Superhero Movies',
		'Partial Blindness',
		'physical condition',
		'Phobia',
		'The government',
		'Fresh Fruit Addiction',
		'An illness or condition',
		'Speech Impediment',
		'footware',
		'Low expectations',
		'Anxiety',
		'Family',
		'Cancer',
		'Uncontrollable Craving',
		'A Secret in his past',
		'Health problem',
		'Inability to collect frequent flyer miles and outrageous luggage fees ',
		'an injury',
		'Smoking',
		'Clothing',
		'Weak immune system',
		'Intolerance of carbohydrates',
		'Red hair and freckles',
		'Impulsive',
		'Easily Derailed',
		'An uncurable nymphomaniac',
		'A castrated man',
		'Physical Handicaps',
		'Inferiority complex',
		'size issues',
		'Dreams',
		'Flying objects',
		'Jewish grandmothers',
		'Uncontrollable Urges',
		'Anything nautical',
		'Breezy locations',
		'A speech impediment',
		'Hunger',
		'Superstition',
		'Allergy to metal',
		'Insomnia',
		'Bitter food',
		'Millions of adoring fans',
		'Decline in business',
		'Being married',
		'Head Equipment',
		'Physiological abnormality',
		'Hereditary Mental Diseases',
		'Mild food poisoning',
		'an insatiable libido',
		'Eyesight',
		'His nemesis',
		'physical defect',
		'time',
		'Brain Problems',
		'Inability to fight',
		'Injury',
		'Academics',
		'epilepsy',
		'Nervous tic',
		'unwanted snow',
		'Inability to hold liquor',
		'Tooth ache',
		'Talkative',
		'Perfection',
		'OCD',
		'Fancy dress',
		'Always smells bad',
		'Old foot injury',
		'Opulence',
		'Rare minerals',
		'His inability to stop spending ',
		'Allergy to an unusual food',
		'Lack of currency',
		'Relatives',
		'Technology',
		'Insects',
		'Sunlight, members of the opposite sex',
		'Love',
		'Physical trait: Resemblance to someone/something',
		'Medical issues',
		'Death',
		'SOCIETY',
		'A fear of a French thing',
		'Rowdy Customers',
		'Extra Appendage',
		'Compulsion: Repetitive',
		'an injury',
		'intelligence',
		'Jokes about his genitals',
		'social awkardness',
		'Tiredness',
		'Battle wounds',
		'physical disability',
		'Conspiracies',
		'Imagination',
		'A very strange phobia',
		'Paper Bags',
		'Physical apperance',
		'Cultural skills',
		'4G coverage',
		'Giant worms',
		'Personality Flaws',
		'Mental Health Issues',
		'Alcoholism',
		'untimely arousal',
		'Each other',
		'Nutritional deficiency',
		'Attitude',
		'Captain Hammer',
		'In love with high-strung individual',
		'Flightless birds',
		'Body Fat',
		'angry black women',
		'The Future',
		'Creepiness',
		'Intellect',
		'The conspiracy of the normal & ordenary',
		'Sexism',
		'knowledge',
		'Explosions',
		'sweet tooth',
		'fear',
		'Dependency',
		'Age',
		'Recent Blindness',
		'Their only weakness',
		'Webcomic Fans',
		'Servere Weather',
		'low self-esteem',
		'Fear of chickens',
		'A local hero',
		'Hubris',
		'Fruits',
		'Suprising stationary',
		'a social inability',
		'Strong alcohol',
		'Technology',
		'Her Size',
		'birth defect',
		'Bad Memory',
		'People of science',
		'Delusions of Grandeur',
		'An obsession',
		'Headaches',
		'Alcoholism',
		'A Superior Hero',
		'Wine',
		'Obsession with murder',
		'Allergic reactions',
		'An illness',
		'Libido',
		'Self-Centered',
		'Fiscal Obligations',
		'Optimism',
		'Dexterity',
		'Uniforms',
		'Politicians',
		'Allergy to something environmental',
		'love of garlic',
		'easily distracted',
		'A Phobia',
		'Living Forever',
		'Propensity for Mischeif',
		'Social Security',
		'Fear of Death',
		'Re-Arranged sense',
		'Thinking Too Hard',
		'Something yet to be invented',
		'Tiny Hands',
		'Scholarly preoccupation',
		'Hobos',
		'Methodical Tendencies',
		'Calenders',
		'Women',
		'Cocky attitude',
		'a strong desire for coconut oil',
		'Government Authorities',
		'His magnetic attraction to danger',
		'Lack of manual dexterity',
		'An Addictive Habit',
		'Shameful secret',
		'Mobility',
		'Fruit',
		'People wearing red',
		'Chaos',
		'Phobia of something absurd',
		'Love',
		'"Personality"',
		'Battery Life',
		'failing vision',
		'inability to pass the driver\'s test',
		'Door Knockers',
		'Medical condition',
		'Speaking Ability',
		'Annoying social habit',
		'Animal Phobia',
		'Relationship Problems',
		'unique limbs',
		'Family issues',
		'His father',
		'Ancient Beings',
		'Restless leg syndrome',
		'Light',
		'fear of discovery',
		'Odour',
		'Attention-seeking',
		'Lactose intolerance',
		'moderate medical condition',
		'Medical condition',
		'A cappella',
		'An old rival',
		'Alergies',
		'Clothing',
		'Gravy',
		'A crippling phobia',
		'Cops',
		'God Complex',
		'Common People',
		'Children',
		'Speech impediment',
		'Uncontrollable urge',
		'Allergies',
		'Memory',
		'Do-gooders',
		'Part of the body where you wouldn\'t want a hole',
		'Easily distracted',
		'Sense of style',
		'unable to swim',
		'his inability to hold his liquor',
		'Phobia of environmental condition',
		'Emotional Issues',
		'Being in-bred',
		'Adam Goldberg',
		'Disability',
		'Attitude problem',
		'Guitar playing',
		'Namecalling',
		'Fear of porcelain',
		'Not mom',
		'crippling debt',
		'Attention Span',
		'Narcolepsy ',
		'missing limb',
		'Monty Python References',
		'Crippling Shame',
		'his brother',
		'Humans',
		'Bugs',
		'An addiction',
		'Murderous urges',
		'Boys',
		'The sea',
		'Sharp metal objects',
		'Exaggerated Personality',
		'Short flights',
		'Fear of women and other pilots',
		'Natural phenomenon',
		'Fear of small animals',
		'genetic abnormality',
		'Mental illness',
		'No depth perception',
		'Addiction to crappy music',
		'Night terrors',
		'Alcohol',
		'Family',
		'Shizophrenia',
		'OCD',
		'False allogations',
		'Insects',
		'Hopeless idealism',
		'Animals',
		'Tourettes syndrome',
		'Parent issues',
		'Superweapons',
		'Bad dreams',
		'Emotional insecurity',
		'confidence issues',
		'Personality',
		'partner',
		'Mysophobia (fear of germs)',
		'personality issues',
		'poverty',
		'The color of his skin',
		'Technology',
		'Allergic to something',
		'Narcolepsy',
		'Bad Breath',
		'Loud noises',
		'no adequate place to socialize',
		'Feet',
		'Debt',
		'ungrammatical sentences',
		'Easily distracted',
		'Bad vision and junk food',
		'His children',
		'an unpleasant biological function',
		'Allergy to plastic',
		'Sunlight',
		'Need for approval',
		'Awarness',
		'Digging',
		'Smells',
		'Motivation',
		'The Sun',
		'Lack of resources',
		'sassy gay men',
		'Extreme Political views',
		'Memories of mother\'s advice',
		'Speech impediment',
		'Lack of cleanliness',
		'Addiction',
		'Health and Safety Protocols',
		'The Man',
		'Impatience',
		'Did something you should never do',
		'strange food',
		'Humans',
		'Good',
		'Nudity',
		'Mob blocking the street',
		'Scared of small animals',
		'Giants',
		'Fear',
		'Colors',
		'Social skill',
		'Bad Habits',
		'Food',
		'A Previous Obligation',
		'Boxes',
		'Artwork',
		'Size',
		'a deep seated fear of cats',
		'Urge to solve the world\'s problems',
		'Bad memory',
		'Disability',
		'too nice',
		'No transportation',
		'Small Objects',
		'Social Phobias',
		'allergies',
		'Fear of children',
		'An irrational hatred of something, anything at all',
		'Strange Need',
		'Miscommunication',
		'A deep moral responsibility',
		'Lack of a skill',
		'Women',
		'Physical Shortcoming',
		'cultural differences',
		'Missing limb',
		'Failing eyesight',
		'A phobia',
		'High Winds',
		'social interactions',
		'Nervous Tick',
		'Social Decorum',
		'Flashing Lights',
		'premature ejaculation',
		'Misshapen Limbs',
		'Allergy to an animal',
		'Lack of thumbs',
		'Bad Stuff',
		'boring sweets',
		'Evil',
		'A rare disease',
		'Personality Quirks',
		'Noise of some kind',
		'Amnesia',
		'Loss of control of bodily functions',
		'Obsession',
		'fear of technology',
		'intelligence',
		'Ankle Problems',
		'Certain words',
		'Violent outbursts when asked a certain question',
		'Need to be liked',
		'Genetic illness',
		'Vision Impairment',
		'Inability to tell things apart',
		'Her inability to have a child',
		'Board Games',
		'Medical Condition',
		'Male-pattern baldness',
		'Body size',
		'Embarassing habit',
		'Pet Project',
		'Suicidal thoughts',
		'Fear of Fish',
		'Speech Impediment',
		'Being a patholigical lier and a constant one upper/glutton for attention',
		'Social anxiety',
		'Naivete',
		'Anarchists',
		'A-list celebs'
	],
	locations: [
		'A moving Vehicle',
		'in a city',
		'a stadium',
		'a tent',
		'The countryside',
		'A convention',
		'the door',
		'Food court',
		'A University',
		'Somewhere fun',
		'UK',
		'In the act of doing something mundane',
		' A sealab',
		'In his trailer',
		'"A shopping facility"',
		'A space station',
		'Boat',
		'a tourist trap',
		'underground',
		'Someplace scenic',
		'Train Station',
		'Someone else\'s dorm room',
		'His parents house',
		'A place many people are afraid of',
		'Shops',
		'Somewhere Safe',
		'Teachers Lounge',
		'His house',
		'basement workshop',
		'An Unsettling Place',
		'Someplace dark',
		'The way to work',
		'A Convention',
		'His rose covered mansion',
		'Somewhere with a great deal of illegal drugs',
		'Train station',
		'an institution',
		'Cracker Barrel',
		'An event that occurs regularly',
		'A place that people go all the time',
		'The Air',
		'On Tour',
		'a convention',
		'A public building',
		'an exciting and playful location',
		'Underground',
		'Public Transportation',
		'His drum set',
		'The Zoo',
		'An awkward social situation',
		'A vehicle hard to access',
		'Park',
		'A place recreationnal',
		'A vehicle',
		'Resturant',
		'Famous landmark',
		'A front for the mob',
		'Underground',
		'Religious retreat',
		'A high mountain walking track',
		'Sporting facility',
		'his workplace',
		'A pub',
		'Mass transit',
		'Deep inside the Earth',
		'A fashion show',
		'a game',
		'Location with children',
		'The Temple',
		'A place where people hide who they are',
		'An adventuring location',
		'Rome',
		'a retail store',
		'A sporting event',
		'The Graveyard',
		'A large, quiet area with armed people in proximity',
		'Hidden Base',
		'A fictional land',
		'World\'s largest mall',
		'the sky above a sprawling metropolis',
		'A closed, window-less room with one other person',
		'The bank',
		'The Temple',
		'Walking his dog',
		'An isolated location',
		'Looking for a new restaurant',
		'A place with a lot of people',
		'the shrubbery fronting Mr. Wei\'s yard',
		'mushrooms',
		'his house',
		'small, enclosed spaces',
		'Tent',
		'A barren mudflat',
		'The top of a famous landmark',
		'the floor',
		'The eternal plane',
		'Golf Course',
		'An Entertainment Venue',
		'The Road Again',
		'The Mall',
		'A Holiday',
		'A zoo exhibit',
		'Work',
		'Manufacturing plant',
		'An Island',
		'At your job',
		'Utah',
		'His office',
		'A rock cliff',
		'Airforce base',
		'Zoo',
		'A setting you are familiar with',
		'Neiman-Marcus',
		'Northern Community',
		'A heist/benefit concert',
		'Vacation',
		'The City',
		'An oceanic vessel',
		'In the act of raising money at a fancy event',
		'arctic expedition',
		'Xbox Live',
		'Church',
		'In the act of getting on the news',
		'Car',
		'A convention',
		'Argentia',
		'a convention',
		'A place where music is played',
		'Ruffly Cubicle Location',
		'Honeymoon',
		'Surrounded by water',
		'Action-filled environment',
		'Pitcher\'s Mound',
		'High Altitude',
		'A place that most would find boring',
		'Police Box',
		'Public Transport',
		'Cofffe shop',
		'a tree',
		'4th period Sociology',
		'a cold place',
		'A public building',
		'A hill',
		'Fleeing his country',
		'A tall building',
		'In the act of doing something he/she will most likely regret',
		'Pagoda',
		'Apartment',
		'In a place he/she most certainly shouldn\'t be',
		'a film set',
		'A TV studio',
		'County Fair',
		'A geographical location that seems unreachable',
		'The beach',
		'A Stage',
		'A bookstore',
		'Public Park',
		'A box',
		'parade float',
		'Basement',
		'Dank Barely Lit Pub',
		'Cinema',
		'High School',
		'time machine',
		'In the basement',
		'A place that evokes a romantic feeling',
		'Somewhere loud',
		'Hiding',
		'her crappy apartment',
		'Shopping district',
		'Her parents\' house',
		'An important phone call',
		'Place with lots of ocean',
		'On the verge of making a big discovery',
		'A relationship',
		'A bathroom',
		'A cliff',
		'A box',
		'Horsey heaven',
		'Sea',
		'Somewhere very crowded',
		'In or on a vehicle that existed 100 years ago',
		'A city',
		'Garage',
		'The wilderness',
		'psychiatrist\'s office',
		'the kiwi farm',
		'Hollywood',
		'A Firefly Class ship',
		'A coffee shop leeching wifi while he sips his Tall Chai Tea',
		'The forest',
		'da bar',
		'Ms. Zona\'s Great Beauty Nails & Hair',
		'A Park',
		'In the act of having an experience they will cherish',
		'A place related to music',
		'A place you can stay in for a long time',
		'A museum',
		'Spain',
		'Here',
		'work',
		'Stationary shop',
		'Her boss\'s house',
		'Inside a trap or cage',
		'Couch',
		' a place with loud music',
		'Rooftop',
		'Where you\'re playing this game',
		'A tall mountain',
		'seat A2 of a jetliner',
		'A cheap sandwich place',
		'Elementry school',
		'A place you can drink',
		'A Local Merchant',
		'A comic convention',
		'A bookshop',
		'A laboratory with lots of bubbling beakers and big machines',
		'A retail store',
		'A convention',
		'In or on a vehicle that goes very fast',
		'High Heat',
		'A location that features nature',
		'The seaside',
		'Ship',
		'Gencon',
		'In or on a vehicle that doesn\'t exist in real life',
		'The moon',
		'A place starting with a random letter of the alphabet',
		'A store',
		'House',
		'A restaraunt',
		'Highway',
		'An old west locale',
		'NYC',
		'Seaworld',
		'A large passenger plane',
		'A famous road',
		'A monument',
		'Driving',
		'A lonely but beautiful place',
		'Audition',
		'Germany',
		'A weapon of mass destruction',
		'A place where good things happen to bad people',
		'a boring place',
		'A dramatic place',
		'A palace',
		'Theripist\'s office',
		'A bar',
		'Great altitude',
		'A hiding place',
		'prayer',
		'Chuck E. Cheese',
		'An amusement park',
		'The World\'s Safest Vacation Locale',
		'On top of something high',
		'a place with high security',
		'A place that inspires security ',
		'A Zoo',
		'Location that is quiet',
		'A very comfy place',
		'A concert',
		'Remote location',
		'Hospital',
		'His cousin\'s secret farm',
		'Cruise ship',
		'Copenhagen',
		'Terrorist training camp',
		'Airport',
		'In a building that will not exist in 100 years',
		'Location with many police officers',
		'A geographical location that seems unreachable',
		'Stadium',
		'Home',
		'A busy location with many people and things',
		'Yacht club',
		'The Country Kitchen Buffet',
		'"Back porch"',
		'Assissted living facitily',
		'A forest',
		'A supermarket',
		'A place where children aren\'t generally allowed',
		'The ruins of a once great kingdom',
		'Her pad',
		'A boat',
		'Boat',
		'a party',
		'Place that some people don\'t believe exists',
		'A hardcore mix of LSD and PCP, plus a Dioxymethalene Concoction',
		'At home',
		'In the act of accomplishing something impossible',
		'retirement home',
		'Fire',
		'Living in the middle of nowhere',
		'Superfund site',
		'Wedding',
		'A place of great historical significance',
		'A Game Convention',
		'In the city',
		'the internet',
		'A geographical location that seems desolate',
		'Work',
		'On stage',
		'An Actor\'s Compound',
		'Famous Landmark',
		'A place in the mall',
		'A place with neon signs',
		'His bedroom',
		'Skatepark',
		'A camping trip',
		'A basement ',
		'Flat',
		'Her Kingdom',
		'A country lane',
		'A place without natural lighting',
		'at a place where national clothing is manufactured',
		'A cabin',
		'A concert',
		'Western Themed Bar',
		'A box',
		'A side street',
		'Nearby Location',
		'A storage area.',
		'A convenience store',
		'Home',
		'A Tropical country',
		'The North Pole',
		'A strangers doorstep',
		'Prairie',
		'lunch',
		'waiting in line',
		'a frozen lake',
		'An amusement ride',
		'His worst nightmare',
		'At sea',
		'Work',
		'In or on a vehicle that only holds one person',
		'"A Shopping Trip"',
		'Shea Stadium',
		'A chain restaurant',
		'A horse',
		'On location',
		'a river or state of being',
		'At home',
		'A musical',
		'In a building that was built over 100 years ago',
		'A Tourist Trap',
		'Comedy festival',
		'Dive school',
		'A government office',
		'Convention Center',
		'at an event',
		'Military vehicle',
		'a cabin a crow\'s flight from judgement day',
		'Space Mission Center',
		'In a building that often has many people inside',
		'Los Angeles Warehouse District',
		'on vacation',
		'Attempting to enter adulthood',
		'Stage performing a song',
		'A large island',
		'Market',
		'A quiet place',
		'A sports field',
		'Amusement Park',
		'Who knows?',
		'a place that famous people frequent',
		'University',
		'House',
		'A school playground',
		'Place he hates shopping',
		'School Excursion',
		'His "Secret Lair"',
		'School',
		'A support group',
		'A store',
		'A dock',
		'A racecourse',
		'a bench',
		'The road',
		'Location without ceilings',
		'riding "Hello Lammy" ',
		'Somewhere lit up at night',
		'In a building that people have died in',
		'A place that seems impenetrable',
		'Strip club',
		'A building site',
		'The highway',
		'Location where she is of great attention',
		'Well-lit area',
		'Overly clean place',
		'Concert Hall',
		'A thing with wheels',
		'A party',
		'The Caribbean Islands',
		'Location with wide, open areas',
		'loveless marriage',
		'Holiday',
		'her office in Brooklyn',
		'Security Booth',
		'A concert festival',
		'adult education class',
		'seminar',
		'The Internet',
		'On a boat',
		'A Movie',
		'A place no one wants to be',
		'an observation platform',
		'A play',
		'a mountain',
		'A fancy winery',
		'Above the snow line',
		'A relative\'s house',
		'Office',
		'Venice',
		'Bad jokes',
		'Trapped someplace you shouldn\'t go',
		'Her studio',
		'A Castle',
		'A lonely place',
		'Halfway',
		'In the act of committing a crime',
		'A Foreign Land',
		'australia',
		'The Airport',
		'A marketplace',
		'His \'fortress\'',
		'Discothèque',
		'A place people pay to enter',
		'a place where large amounts of alcohol are imbued',
		'A graveyard',
		'Ridin\' The Rails',
		'A melancholic place',
		'A Convience Store',
		'Space Station',
		'A place people honeymoon',
		'a Las Vegas Hotel',
		'at the front desk',
		'A nondescript convienince store',
		'A scary place',
		'Adelaide',
		'At sea',
		'A park.',
		'Chicago',
		'His store',
		'Zoo Exhibit',
		'Mansion',
		'Somewhere lonely',
		'Trapped in a place with lots of tourists',
		'A very large, empty room',
		'In a foreign land',
		'Dubai',
		'A dank, smelly apartment',
		'a drug rehab',
		'Very damp location',
		'A tunnel',
		'Famous Landmark',
		'Restaurant',
		'His basement',
		'Intellectual event',
		'A place everybody has heard of',
		'Stadium',
		'Greyhound bus terminal',
		'The midst of sad suburban sprawl',
		'Chicago',
		'Hospital',
		'Inside your head cafe',
		'A natural feature',
		'a farmer\'s market',
		'A World Tour',
		'A fancy Hotel',
		'a cheap motel room',
		'Something inflatable',
		'Daycare',
		'Welfare Office',
		'Place of learning',
		'Imaginary Place',
		'High Place',
		'building a colony that will go to the moon someday',
		'A rustic chapel',
		'A bay on the northern Scottish coast',
		'the FBI headquarters',
		'grocery store',
		'Impregnable hideout',
		'a forested area',
		'route to the airport',
		'Dinosaur',
		'A Sports Arena',
		'A bar',
		'A very tall structure',
		'A form of transport',
		'A Nightclub',
		'Somewhere hidden',
		'The ice',
		'Abattoir',
		'A place under the ground',
		'Hardware store',
		'The real Kelsey Grammer\'s property',
		'A place with lots of people',
		'A small town',
		'South Florida',
		'School',
		'Cleveland, Ohio',
		'The Green Dragon Tavern',
		'Lives near family',
		'A machine',
		'The Gym',
		'In the act of getting on the news',
		'pyramids',
		'antique store',
		'A local hotspot',
		'A trip',
		'a party',
		'The Theatre',
		'A Funeral',
		'His brewery',
		'His Apartment',
		'A place people want to go',
		'A public place',
		'A bookshop',
		'A station',
		'Perpetually in a montage.',
		'A lab testing shampoo',
		'A building',
		'The process of making someone a  vampire',
		'construction site',
		'His car',
		'Somewhere nefarious',
		'The beach',
		'A geographical location that\'s very dangerous',
		'His computer desk',
		'Church',
		'Zoo',
		'A train station',
		'The beach',
		'In the act of doing something they will regret',
		'Place where unions are formed',
		'Childrens playground',
		'Drugs',
		'The New Yorker Diner',
		'waiting in line',
		'At home',
		'A boat',
		'football field',
		'Sustainable Transportation',
		'A Sporting Event',
		'A Hospital Facility',
		'mall',
		'Another planet',
		'A place where nothing bad could ever happen',
		'Labrotory',
		'The driver\'s seat of a greyhound bus',
		'A Blacked Out Vehicle',
		'at home',
		'A place where you might find good food',
		'Trade Expo/Convention',
		'A rundown Titty Bar',
		'a place of great commotion',
		'Something that looks like a pitted avocado',
		'Medical Office',
		'An event',
		'Mansion',
		'Chicago',
		'A pond',
		'On the open road',
		'A place of work',
		'A place one can find unique objects',
		'a Private Yacht',
		'Working',
		'Space',
		'A very dark place',
		'Peru',
		'Performing',
		'a nail salon',
		'A big box store',
		'A small blue-green planet where people still think digital watches are a "pretty neat idea"',
		'Botanic Gardens',
		'A geographical location that no person has ever been',
		'the alleyway behind a motel',
		'An appointment',
		'A parking lot',
		'Jousting tournament',
		'anywhere that needs a heavy dose of comptrolling',
		'Airport',
		'Professional setting',
		'Stage',
		'Hospital',
		'A location with many people',
		'car seat',
		'embarrasingly empty yacht party',
		'The Professor\'s Office',
		'a hair studio',
		'A prior living situation',
		'Somewhere cold',
		'Home',
		'the desert',
		'another adventure',
		'Thin Ice',
		'A place that is hidden',
		'Somewhere suspicious',
		'Renesance Fair',
		'A motorized vehicle',
		'A mall',
		'Important Social Event',
		'vacation',
		'A Date, somehow',
		'Underground',
		'A remote place',
		'out "job-searching"',
		'A crypt',
		'A place that only holds one person',
		'A canoe in the rainforest',
		'Palace',
		'A place with tons of people looking at him as if he is crazy',
		'Event',
		'Department store',
		'At a Comic Convention',
		' In a raft',
		'A Castle',
		'A place with 360-degree views',
		'A fairground',
		'Municipal infrastructure',
		'An animal shelter',
		'Something in the sky',
		'Hospital',
		'a sky scraper',
		'a cinema',
		'Home',
		'in Africa',
		'Vacation',
		'a sport arena',
		'suburban townhome',
		'A Hoe-Down',
		'A Stylish hangout',
		'A volcanic caldera',
		'San Diego',
		'"Ernie\'s" house ',
		'Dog show',
		'A place that feels secure',
		'the scene of a famous speech',
		'SXSW',
		'University',
		'In or on a vehicle that flies',
		'A computer',
		'The theatre',
		'an uncomfortable public place',
		'In or on a vehicle that requires multiple people to control',
		'Cemetary',
		'Yacht',
		'Museum',
		'Hole',
		'The lot of his dealership',
		'Crete',
		'Lighthouse',
		'A Delorean',
		'dance club',
		'Gym',
		'Old growth forest',
		'"A soda plant"',
		'a festival',
		'Dirty, Old House',
		'Down Under',
		'A traffic light ',
		'A prison cell',
		'Somewhere Romantic',
		'on the road',
		'A server',
		'In Hiding',
		'Nature & art festival',
		'A mission from God',
		'Enclosed public space',
		'A presidential campaign',
		'A landmark',
		'on the way to a job',
		'Trapped in an enclosed space',
		'Shopping',
		'Trapped in a place with animals',
		'a road',
		'A church',
		'Festival',
		'a mission',
		'at the hospital',
		'Backpacking through Japan',
		'a plane',
		'A Workplace',
		'brasil',
		'Home',
		'A Sports Arena',
		'Class',
		'the Venice Beach Starbucks',
		'Grand opening',
		'In a building that you\'ve never been inside',
		'A large enclosed space',
		'A place tourists are not welcome',
		'A famous sports stadium',
		'A major city',
		'Deep Red Leather Armchair',
		'House',
		'a place with a lot of babies',
		'a hit',
		'Labratory',
		'Trapped in a place where leaving would be dangerous',
		'Hungary',
		'some major corporation',
		'on a Boat',
		'Geocacher\'s Symposium',
		'Flying Disc',
		'movie editing studio',
		'The job',
		'In a building that has a lot of different types of people in it',
		'Central Park',
		'Somewhere',
		'a small sea-side town',
		'A quest',
		'A pizza joint',
		'A Venesuelan jungle',
		'A place where people go for fun',
		'Travelling circus',
		'Somewhere easy to get disorientated in',
		'a local park',
		'british museum',
		'a studo apartment',
		'Minnesota',
		'A spiritual journey',
		'The one place where he can die a happy man',
		'Stadium',
		'Hospital',
		'A location with many people and security',
		'An abandoned cathedral',
		'A bistro',
		'Casino',
		'Dental Surgery',
		'A dangerous dockside bar',
		'Trapped in a place after hours',
		'a place full of fattys',
		'Somewhere unexpected',
		'Home',
		'Circus',
		'Store',
		'At a party',
		'Unknown',
		'Malaysia',
		'The Hobo Palace',
		'Air Force One'
	],
	predictions: [
		'FORK',
		'WAITER',
		'FAN BLADE',
		'SWEDISH',
		'CHEWING',
		'PET',
		'FALLING ICE',
		'STAIRS',
		'Blowing in the breeze, twisting in the',
		'STAPLES',
		'PAINT FUMES',
		'PEN',
		'DROPPED',
		'HOT PEPPER',
		'CURLING IRON',
		'CANE',
		'VIBRATION',
		'FREE SAMPLES',
		'BLOWN AWAY',
		'LOVESTRUCK',
		'TURNSTILE',
		'LETTER OPENER',
		'COPPER',
		'STUDENT DRIVER',
		'SOFA',
		'STOMPED',
		'CHOCOLATE',
		'ULTRASOUND',
		'FERAL CATS',
		'HEAD STUCK',
		'PERFORMANCE',
		'CINDER BLOCK',
		'BIPOLAR BEAR',
		'MOTORCYCLE',
		'PENGUINS',
		'SNOWED IN',
		'OVERSIZED',
		'LIVER',
		'TAMPERING',
		'LIMB',
		'GLUE',
		'EARBLEED',
		'STUFFED',
		'BELT',
		'WET TILE',
		'BLOWFISH',
		'BUS',
		'BOUNCER',
		'GARBAGE TRUCK',
		'PANTS ON FIRE',
		'COMB',
		'TRASH',
		'ROCK',
		'DEEP FRYER',
		'ARMOIRE',
		'FRYING PAN',
		'BRAIN M ELT',
		'BONED',
		'BRAIN FREEZE',
		'TATTOO',
		'NANOBOTS',
		'FLU',
		'WHEELS',
		'STEAMED',
		'FOAM',
		'BAD S IGNAGE',
		'BANANA PEEL',
		'SCISSORS',
		'CURRENT',
		'FRENCH PRESS',
		'DARKNESS',
		'SWALLOW',
		'CANOE',
		'FLOSS',
		'PILLOW',
		'RAIL',
		'CLOGS',
		'THUMBTACK',
		'CHAIN',
		'SCAFFOLD',
		'LAUNCH',
		'AEROSOL',
		'MANNEQUIN',
		'CLOWNING',
		'NUKED',
		'YACHT',
		'RULER',
		'BOILS',
		'KNIGHT',
		'STUD',
		'ROAD RAGE',
		'HUMMINGBIRDS',
		'STOCKS',
		'SHOWER',
		'STROKE',
		'ACID',
		'WAX',
		'SNAPPED',
		'CANDLE',
		'PLASTERED',
		'TOXIC MOTH',
		'FOOD F IGHT',
		'MUSHROOM',
		'PUPPET',
		'THERMONUCLEAR EXPLOSION',
		'FREEDOM',
		'MACE',
		'BASS',
		'FEEDBACK',
		'MIME',
		'LUCKY CHARM',
		'POKER',
		'MUMMY',
		'RUBBER',
		'SLIPPED DISC',
		'MISSED A S TEP',
		'COW PIE',
		'WING',
		'TREBUCHET',
		'SPRITE',
		'BUBBLE',
		'DOUBLE I RONY',
		'MANUFACTURING DEFECT',
		'HORSE',
		'KINDERGARTEN CLASS',
		'RECYCLING',
		'TOAST',
		'WHISKY',
		'YARN',
		'STUDENT ROBOT',
		'BAD B LOOD',
		'KINDNESS',
		'CARTOON',
		'SIDE EFFECTS',
		'BUGS',
		'FORCE',
		'TAXES',
		'GEEK',
		'REVOLVING DOOR',
		'SPRING BREAK',
		'AVERSION THERAPY',
		'DANE',
		'CHOPS',
		'SPANDREL',
		'FIRST STEP',
		'HELIX',
		'LIQUID NITROGEN',
		'ANVIL',
		'TURNIP',
		'BLACK HOLE',
		'WAITING IN LINE',
		'MISSIONARY',
		'CHILDHOOD WISH',
		'SOUS VIDE',
		'BUTTERFLY',
		'COINCIDENCE',
		'GOAT THONG',
		'SUPERNATURAL',
		'NERD RAGE',
		'ARTICHOKE',
		'CHAPS',
		'HELIUM',
		'YETI',
		'ZOMBIE',
		'STRANGLED WITH OWN JEJUNUM',
		'FORMULA',
		'PLAYING CARD',
		'TOLLBOOTH',
		'MOLTEN GOLD',
		'SELECTION',
		'CORGI',
		'DISINTEGRATION',
		'LEGION OF GNOMES',
		'A DEAD MOOSE',
		'BEING TOO SPECIFIC',
		'THE FUTURE (BUT IT\'S REALLY THE PAST)',
		'CLAMS',
		'BEARD STUBBLE',
		'INNOVATION',
		'DEATH PANEL',
		'WEB',
		'BONE CHOKING',
		'TAPE',
		'THE GRID',
		'KITTENS'
	],
	getRandom: function(arr){
		return arr[Math.floor(Math.random()*arr.length)];
	},
	generateTarget: function(){
		return {
			firstName: targets.getRandom(targets.firstNames),
			lastName: targets.getRandom(targets.lastNames),
			excitedBy: targets.getRandom(targets.excitedBy),
			hinderedBy: targets.getRandom(targets.hinderedBy),
			location: targets.getRandom(targets.locations),
			prediction: targets.getRandom(targets.predictions),
			knowsPrediction: Math.floor(Math.random()*2)
		};
	}
};